[package]
name = "ftp-brutal"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ftp-brutal"
path = "src/v2/main.rs"

[dependencies]
ftp = "3.0.1"
tokio = { version = "1.34.0", features = ["full"] }
