[package]
name = "ftp-brutal"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ftp-brutal"
path = "src/v2/main.rs"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
log = "0.4"
tokio = { version = "1.34.0", features = ["full"] }
simple_logger = "4.2.0"
ftp = "3.0.1"