version: '3'

services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp-server
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./ftp-data:/home/vsftpd/data
    environment:
      - FTP_USER=johndoe
      - FTP_PASS=iloveu
      - PASV_ADDRESS=127.0.0.2